import test from 'node:test';
import assert from 'node:assert/strict';
import {installReplayDedup} from '../../vendor/dsh-replay-dedup/src/runtime.js';
import {apply as coerce} from '../../vendor/dsh-tool-arg-coerce/lib/index.js';
const message={type:'warn',args:['unusable replay state','route-a']};
function logger(){const delivered=[[],[]];const exporters=new Map(delivered.map((out,i)=>[i,{export(m){out.push(m)}}]));return {delivered,exporters,exporter(e){this.exporters.set(2,e);return ()=>this.exporters.delete(2);}};}
test('each exporter receives the first warning',()=>{const s=logger(),done=installReplayDedup(s);for(const e of s.exporters.values()){e.export(message);e.export(message);}assert.deepEqual(s.delivered.map(d=>d.length),[1,1]);done();});
test('dispose restores existing exporters and the registration method',()=>{const s=logger(),orig=s.exporter,f=s.exporters.get(0).export,done=installReplayDedup(s);done();assert.equal(s.exporter,orig);assert.equal(s.exporters.get(0).export,f);s.exporters.get(0).export(message);s.exporters.get(0).export(message);assert.equal(s.delivered[0].length,2);});
test('future exporter registration and disposal are owned',()=>{const s=logger(),done=installReplayDedup(s),messages=[],e={export:m=>messages.push(m)},original=e.export;const remove=s.exporter(e);e.export(message);e.export(message);assert.equal(messages.length,1);remove();assert.equal(e.export,original);done();});
test('expiry and distinct routes are not silently merged',()=>{const s=logger();let now=0;const done=installReplayDedup(s,{windowMs:10,now:()=>now}),e=s.exporters.get(0);e.export(message);e.export({...message,args:[message.args[0],'route-b']});now=10;e.export(message);assert.equal(s.delivered[0].length,3);done();});
test('repeated mounts retain active wrappers until last owner releases',()=>{const s=logger(),a=installReplayDedup(s),b=installReplayDedup(s),e=s.exporters.get(0);a();e.export(message);e.export(message);assert.equal(s.delivered[0].length,1);b();e.export(message);assert.equal(s.delivered[0].length,2);});
test('non-replay warnings and errors are never deduplicated',()=>{const s=logger(),done=installReplayDedup(s),e=s.exporters.get(0);for(let i=0;i<2;i++){e.export({type:'warn',args:['other']});e.export({type:'error',args:message.args});}assert.equal(s.delivered[0].length,4);done();});
test('bounded map permits an evicted route rather than growing forever',()=>{const s=logger(),done=installReplayDedup(s,{maxKeys:1}),e=s.exporters.get(0);e.export(message);e.export({...message,args:[message.args[0],'other']});e.export(message);assert.equal(s.delivered[0].length,3);done();});
test('coerce fail-success-fail resets its per-tool streak',async()=>{const handlers={};coerce({on:(name,fn)=>handlers[name]=fn,effect:()=>{}});const exec={name:'glob',arguments:{description:'nonsense'},agent:{session:{id:'one'}}};const fail={isError:true,error:{message:'invalid arguments: missing required property pattern'}};const accept=async()=>({kind:'accept'});await handlers['tools/post-execute'](exec,fail,accept);await handlers['tools/post-execute'](exec,{isError:false},accept);const result=await handlers['tools/post-execute'](exec,fail,accept);assert.ok(!result.content[0].text.includes('Hint:'));});
